//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Forms.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Data", Namespace="http://plot.org/")]
    [System.SerializableAttribute()]
    public partial class Data : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        private System.DateTime BDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SpecField;
        
        private int SYearField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public System.DateTime BDate {
            get {
                return this.BDateField;
            }
            set {
                if ((this.BDateField.Equals(value) != true)) {
                    this.BDateField = value;
                    this.RaisePropertyChanged("BDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Spec {
            get {
                return this.SpecField;
            }
            set {
                if ((object.ReferenceEquals(this.SpecField, value) != true)) {
                    this.SpecField = value;
                    this.RaisePropertyChanged("Spec");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int SYear {
            get {
                return this.SYearField;
            }
            set {
                if ((this.SYearField.Equals(value) != true)) {
                    this.SYearField = value;
                    this.RaisePropertyChanged("SYear");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://plot.org/", ConfigurationName="ServiceReference1.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://plot.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://plot.org/HelloWorld", ReplyAction="*")]
        Forms.ServiceReference1.HelloWorldResponse HelloWorld(Forms.ServiceReference1.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://plot.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<Forms.ServiceReference1.HelloWorldResponse> HelloWorldAsync(Forms.ServiceReference1.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name GetDictResult from namespace http://plot.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://plot.org/GetDict", ReplyAction="*")]
        Forms.ServiceReference1.GetDictResponse GetDict(Forms.ServiceReference1.GetDictRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://plot.org/GetDict", ReplyAction="*")]
        System.Threading.Tasks.Task<Forms.ServiceReference1.GetDictResponse> GetDictAsync(Forms.ServiceReference1.GetDictRequest request);
        
        // CODEGEN: Generating message contract since element name data from namespace http://plot.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://plot.org/AddDict", ReplyAction="*")]
        Forms.ServiceReference1.AddDictResponse AddDict(Forms.ServiceReference1.AddDictRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://plot.org/AddDict", ReplyAction="*")]
        System.Threading.Tasks.Task<Forms.ServiceReference1.AddDictResponse> AddDictAsync(Forms.ServiceReference1.AddDictRequest request);
        
        // CODEGEN: Generating message contract since element name data from namespace http://plot.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://plot.org/UdpDict", ReplyAction="*")]
        Forms.ServiceReference1.UdpDictResponse UdpDict(Forms.ServiceReference1.UdpDictRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://plot.org/UdpDict", ReplyAction="*")]
        System.Threading.Tasks.Task<Forms.ServiceReference1.UdpDictResponse> UdpDictAsync(Forms.ServiceReference1.UdpDictRequest request);
        
        // CODEGEN: Generating message contract since element name data from namespace http://plot.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://plot.org/DelDict", ReplyAction="*")]
        Forms.ServiceReference1.DelDictResponse DelDict(Forms.ServiceReference1.DelDictRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://plot.org/DelDict", ReplyAction="*")]
        System.Threading.Tasks.Task<Forms.ServiceReference1.DelDictResponse> DelDictAsync(Forms.ServiceReference1.DelDictRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://plot.org/", Order=0)]
        public Forms.ServiceReference1.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(Forms.ServiceReference1.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://plot.org/", Order=0)]
        public Forms.ServiceReference1.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(Forms.ServiceReference1.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://plot.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDictRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDict", Namespace="http://plot.org/", Order=0)]
        public Forms.ServiceReference1.GetDictRequestBody Body;
        
        public GetDictRequest() {
        }
        
        public GetDictRequest(Forms.ServiceReference1.GetDictRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetDictRequestBody {
        
        public GetDictRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDictResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDictResponse", Namespace="http://plot.org/", Order=0)]
        public Forms.ServiceReference1.GetDictResponseBody Body;
        
        public GetDictResponse() {
        }
        
        public GetDictResponse(Forms.ServiceReference1.GetDictResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://plot.org/")]
    public partial class GetDictResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Forms.ServiceReference1.Data[] GetDictResult;
        
        public GetDictResponseBody() {
        }
        
        public GetDictResponseBody(Forms.ServiceReference1.Data[] GetDictResult) {
            this.GetDictResult = GetDictResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddDictRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddDict", Namespace="http://plot.org/", Order=0)]
        public Forms.ServiceReference1.AddDictRequestBody Body;
        
        public AddDictRequest() {
        }
        
        public AddDictRequest(Forms.ServiceReference1.AddDictRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://plot.org/")]
    public partial class AddDictRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Forms.ServiceReference1.Data data;
        
        public AddDictRequestBody() {
        }
        
        public AddDictRequestBody(Forms.ServiceReference1.Data data) {
            this.data = data;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddDictResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddDictResponse", Namespace="http://plot.org/", Order=0)]
        public Forms.ServiceReference1.AddDictResponseBody Body;
        
        public AddDictResponse() {
        }
        
        public AddDictResponse(Forms.ServiceReference1.AddDictResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class AddDictResponseBody {
        
        public AddDictResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UdpDictRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UdpDict", Namespace="http://plot.org/", Order=0)]
        public Forms.ServiceReference1.UdpDictRequestBody Body;
        
        public UdpDictRequest() {
        }
        
        public UdpDictRequest(Forms.ServiceReference1.UdpDictRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://plot.org/")]
    public partial class UdpDictRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Forms.ServiceReference1.Data data;
        
        public UdpDictRequestBody() {
        }
        
        public UdpDictRequestBody(Forms.ServiceReference1.Data data) {
            this.data = data;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UdpDictResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UdpDictResponse", Namespace="http://plot.org/", Order=0)]
        public Forms.ServiceReference1.UdpDictResponseBody Body;
        
        public UdpDictResponse() {
        }
        
        public UdpDictResponse(Forms.ServiceReference1.UdpDictResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class UdpDictResponseBody {
        
        public UdpDictResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DelDictRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DelDict", Namespace="http://plot.org/", Order=0)]
        public Forms.ServiceReference1.DelDictRequestBody Body;
        
        public DelDictRequest() {
        }
        
        public DelDictRequest(Forms.ServiceReference1.DelDictRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://plot.org/")]
    public partial class DelDictRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Forms.ServiceReference1.Data data;
        
        public DelDictRequestBody() {
        }
        
        public DelDictRequestBody(Forms.ServiceReference1.Data data) {
            this.data = data;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DelDictResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DelDictResponse", Namespace="http://plot.org/", Order=0)]
        public Forms.ServiceReference1.DelDictResponseBody Body;
        
        public DelDictResponse() {
        }
        
        public DelDictResponse(Forms.ServiceReference1.DelDictResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class DelDictResponseBody {
        
        public DelDictResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : Forms.ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<Forms.ServiceReference1.WebService1Soap>, Forms.ServiceReference1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Forms.ServiceReference1.HelloWorldResponse Forms.ServiceReference1.WebService1Soap.HelloWorld(Forms.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            Forms.ServiceReference1.HelloWorldRequest inValue = new Forms.ServiceReference1.HelloWorldRequest();
            inValue.Body = new Forms.ServiceReference1.HelloWorldRequestBody();
            Forms.ServiceReference1.HelloWorldResponse retVal = ((Forms.ServiceReference1.WebService1Soap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Forms.ServiceReference1.HelloWorldResponse> Forms.ServiceReference1.WebService1Soap.HelloWorldAsync(Forms.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<Forms.ServiceReference1.HelloWorldResponse> HelloWorldAsync() {
            Forms.ServiceReference1.HelloWorldRequest inValue = new Forms.ServiceReference1.HelloWorldRequest();
            inValue.Body = new Forms.ServiceReference1.HelloWorldRequestBody();
            return ((Forms.ServiceReference1.WebService1Soap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Forms.ServiceReference1.GetDictResponse Forms.ServiceReference1.WebService1Soap.GetDict(Forms.ServiceReference1.GetDictRequest request) {
            return base.Channel.GetDict(request);
        }
        
        public Forms.ServiceReference1.Data[] GetDict() {
            Forms.ServiceReference1.GetDictRequest inValue = new Forms.ServiceReference1.GetDictRequest();
            inValue.Body = new Forms.ServiceReference1.GetDictRequestBody();
            Forms.ServiceReference1.GetDictResponse retVal = ((Forms.ServiceReference1.WebService1Soap)(this)).GetDict(inValue);
            return retVal.Body.GetDictResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Forms.ServiceReference1.GetDictResponse> Forms.ServiceReference1.WebService1Soap.GetDictAsync(Forms.ServiceReference1.GetDictRequest request) {
            return base.Channel.GetDictAsync(request);
        }
        
        public System.Threading.Tasks.Task<Forms.ServiceReference1.GetDictResponse> GetDictAsync() {
            Forms.ServiceReference1.GetDictRequest inValue = new Forms.ServiceReference1.GetDictRequest();
            inValue.Body = new Forms.ServiceReference1.GetDictRequestBody();
            return ((Forms.ServiceReference1.WebService1Soap)(this)).GetDictAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Forms.ServiceReference1.AddDictResponse Forms.ServiceReference1.WebService1Soap.AddDict(Forms.ServiceReference1.AddDictRequest request) {
            return base.Channel.AddDict(request);
        }
        
        public void AddDict(Forms.ServiceReference1.Data data) {
            Forms.ServiceReference1.AddDictRequest inValue = new Forms.ServiceReference1.AddDictRequest();
            inValue.Body = new Forms.ServiceReference1.AddDictRequestBody();
            inValue.Body.data = data;
            Forms.ServiceReference1.AddDictResponse retVal = ((Forms.ServiceReference1.WebService1Soap)(this)).AddDict(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Forms.ServiceReference1.AddDictResponse> Forms.ServiceReference1.WebService1Soap.AddDictAsync(Forms.ServiceReference1.AddDictRequest request) {
            return base.Channel.AddDictAsync(request);
        }
        
        public System.Threading.Tasks.Task<Forms.ServiceReference1.AddDictResponse> AddDictAsync(Forms.ServiceReference1.Data data) {
            Forms.ServiceReference1.AddDictRequest inValue = new Forms.ServiceReference1.AddDictRequest();
            inValue.Body = new Forms.ServiceReference1.AddDictRequestBody();
            inValue.Body.data = data;
            return ((Forms.ServiceReference1.WebService1Soap)(this)).AddDictAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Forms.ServiceReference1.UdpDictResponse Forms.ServiceReference1.WebService1Soap.UdpDict(Forms.ServiceReference1.UdpDictRequest request) {
            return base.Channel.UdpDict(request);
        }
        
        public void UdpDict(Forms.ServiceReference1.Data data) {
            Forms.ServiceReference1.UdpDictRequest inValue = new Forms.ServiceReference1.UdpDictRequest();
            inValue.Body = new Forms.ServiceReference1.UdpDictRequestBody();
            inValue.Body.data = data;
            Forms.ServiceReference1.UdpDictResponse retVal = ((Forms.ServiceReference1.WebService1Soap)(this)).UdpDict(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Forms.ServiceReference1.UdpDictResponse> Forms.ServiceReference1.WebService1Soap.UdpDictAsync(Forms.ServiceReference1.UdpDictRequest request) {
            return base.Channel.UdpDictAsync(request);
        }
        
        public System.Threading.Tasks.Task<Forms.ServiceReference1.UdpDictResponse> UdpDictAsync(Forms.ServiceReference1.Data data) {
            Forms.ServiceReference1.UdpDictRequest inValue = new Forms.ServiceReference1.UdpDictRequest();
            inValue.Body = new Forms.ServiceReference1.UdpDictRequestBody();
            inValue.Body.data = data;
            return ((Forms.ServiceReference1.WebService1Soap)(this)).UdpDictAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Forms.ServiceReference1.DelDictResponse Forms.ServiceReference1.WebService1Soap.DelDict(Forms.ServiceReference1.DelDictRequest request) {
            return base.Channel.DelDict(request);
        }
        
        public void DelDict(Forms.ServiceReference1.Data data) {
            Forms.ServiceReference1.DelDictRequest inValue = new Forms.ServiceReference1.DelDictRequest();
            inValue.Body = new Forms.ServiceReference1.DelDictRequestBody();
            inValue.Body.data = data;
            Forms.ServiceReference1.DelDictResponse retVal = ((Forms.ServiceReference1.WebService1Soap)(this)).DelDict(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Forms.ServiceReference1.DelDictResponse> Forms.ServiceReference1.WebService1Soap.DelDictAsync(Forms.ServiceReference1.DelDictRequest request) {
            return base.Channel.DelDictAsync(request);
        }
        
        public System.Threading.Tasks.Task<Forms.ServiceReference1.DelDictResponse> DelDictAsync(Forms.ServiceReference1.Data data) {
            Forms.ServiceReference1.DelDictRequest inValue = new Forms.ServiceReference1.DelDictRequest();
            inValue.Body = new Forms.ServiceReference1.DelDictRequestBody();
            inValue.Body.data = data;
            return ((Forms.ServiceReference1.WebService1Soap)(this)).DelDictAsync(inValue);
        }
    }
}
